trigger: none
repositories:
- repository: JiraDeployInfo
    type: github
    name: educationperfect/azure-jira-update
stages:
  - stage: DeployTest
    jobs:
      - deployment: Test
        environment: "testjira"
        pool:
          name: Generic Linux Agents
          demands: docker
        workspace:
          clean: all
        strategy:
          runOnce:
            preDeploy:
              steps:
                - {template: update-jira.yml@JiraDeployInfo, parameters: { JiraState: "Pending", JiraEnvironment: "Testing", JiraDomain: "companyname.atlassian.net" }} 
                # JiraState can be one of "Unknown", "Pending", "InProgress", "Cancelled", "Failed", "RolledBack", "Successful"
                # JiraEnvironment can one of "Unmapped", "Development", "Testing", "Staging", "Production"
            on:
              failure:
                steps:
                  - {template: update-jira.yml@JiraDeployInfo, parameters: { JiraState: "Failed", JiraEnvironment: "Testing", JiraDomain: "companyname.atlassian.net" }}
              success: 
                steps:
                  - {template: update-jira.yml@JiraDeployInfo, parameters: { JiraState: "Successful", JiraEnvironment: "Testing", JiraDomain: "companyname.atlassian.net" }}
            deploy:
              steps:
                - {template: update-jira.yml@JiraDeployInfo, parameters: { JiraState: "InProgress", JiraEnvironment: "Testing", JiraDomain: "companyname.atlassian.net" }}
                ...